.vars-image-gooddata:
  variables:
    PYTHON_IMAGE: "python:3.10.11-slim-bullseye"
    DBT_GOODDATA_IMAGE_BASE: "gooddata-data-pipeline-dbt-gooddata"
    DBT_GOODDATA_VERSION: "1.11.1.dev1"
    DBT_GOODDATA_IMAGE: "$CI_REGISTRY_IMAGE/$DBT_GOODDATA_IMAGE_BASE:$DBT_GOODDATA_VERSION"
